## 开发时使用h2db数据库，上线时需要切换到mysql。切换到mysql需要手动创建数据库，然后执行resource目录下的sql语句。

#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/wx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#        username: ${MYSQL_USERNAME:root}
#        password: ${MYSQL_PASSWORD:123456}

spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./channel_server;AUTO_SERVER=TRUE;MODE=MySQL
        username: sa
        password:
        initialization-mode: always
        data: classpath:sql/data.sql
        continue-on-error: true
        ##spring.datasource.initialization-mode为always时，每次启动都会初始化resource目录下的data.sql日志，如果上线，需要注释掉initialization-mode和data配置，然后手动初始化数据库。

springfox:
    documentation:
        swagger-ui:
            enabled: false